import { BlogFaq } from '../blog/types'
import type { GuideMeta } from './types'

export const slug = 'kindle-formats'
export const title = 'Kindle Formats Explained: AZW3, KFX, MOBI & What to Convert To'
export const problem = 'AZW3, KFX, MOBI, EPUB — Kindle’s format soup confuses everyone. Here is what each means and the safest format to convert to today.'
export const date = '2026-08-07'
export const tags = ['kindle formats', 'azw3', 'kfx', 'mobi', 'send to kindle']
export const keyTakeaways = [
  'Amazon’s Send to Kindle accepts EPUB and AZW3 and converts them for your device.',
  'MOBI side-loading is retired; don’t convert new books to MOBI for Kindle.',
  'KFX is Amazon’s proprietary format — you can’t easily create it yourself.',
  'For sideloading, AZW3 is the most compatible format BookConv can produce.',
]
export const formats = { source: 'epub', target: 'azw3' }
export const content = {
  intro: 'Kindle readers don’t take “any ebook.” Over the years Amazon moved from MOBI to AZW3 and now to KFX, while Send to Kindle added EPUB support. This page untangles the formats so you convert to the right one instead of a file your Kindle rejects.',
  sections: [
    {
      heading: 'The Kindle format landscape',
      body: `**MOBI:** the old standard. Amazon retired MOBI side-loading, so new uploads in MOBI are no longer the recommended path.\n\n**AZW3:** Amazon’s modern ebook format with better typography and features; widely supported by Kindle devices.\n\n**KFX:** Amazon’s current proprietary format with advanced layout; created by Amazon’s own pipeline, not easily produced by third-party converters.\n\n**EPUB:** the open standard. Send to Kindle now accepts EPUB and converts it for your device.`,
    },
    {
      heading: 'What to convert to (practical rule)',
      body: `**For sideloading a file yourself:** convert to **AZW3** — BookConv can produce it and Kindles read it well.\n\n**For Send to Kindle:** upload **EPUB or AZW3** and let Amazon convert.\n\n**Avoid:** converting new books to MOBI, and trying to generate KFX yourself.`,
    },
    {
      heading: 'Common Kindle conversion paths',
      body: `**EPUB → AZW3** for sideloading: [EPUB to AZW3](/convert/epub-to-azw3).\n\n**AZW3 → PDF** if you need a fixed-layout printout: [AZW3 to PDF](/convert/azw3-to-pdf).\n\n**MOBI → EPUB/AZW3** to modernize an old library: [Mobi to EPUB](/convert/mobi-to-epub).`,
    },
    {
      heading: 'Why not just use MOBI?',
      body: `MOBI is legacy. Amazon’s Send to Kindle no longer prioritizes it, and newer features only exist in AZW3/KFX. Converting new content to MOBI risks a file your device handles poorly.\n\nIf you already own MOBI files, convert them forward to AZW3 rather than keeping the old format.`,
    },
  ],
}
export const faqs: BlogFaq[] = [
  { question: 'What format should I convert to for Kindle?', answer: 'For sideloading, AZW3 is the most compatible format BookConv can produce. For Send to Kindle, upload EPUB or AZW3 and Amazon converts it.' },
  { question: 'Is MOBI still supported on Kindle?', answer: 'Amazon retired MOBI side-loading; Send to Kindle now favors EPUB and AZW3. Converting new books to MOBI is no longer recommended.' },
  { question: 'What is KFX and can I create it?', answer: 'KFX is Amazon’s proprietary format with advanced layout. It is generated by Amazon’s own pipeline, so third-party converters generally can’t create true KFX. Convert to AZW3 instead.' },
  { question: 'Can BookConv convert EPUB to a Kindle format?', answer: 'Yes. BookConv converts EPUB to AZW3, which Kindles read well, and you can also send EPUB to Kindle via Amazon’s Send to Kindle.' },
  { question: 'How do I modernize an old MOBI library?', answer: 'Convert MOBI forward to AZW3 (or EPUB) with BookConv so your files use a current, well-supported format.' },
]
