// src/lib/keywords/competitor.ts
// Types + pure helpers for data/competitor-series.json.
//
// Generated by scripts/build-competitor-series.mjs from daily
// 数据分析/competitor-serp-*.json snapshots. This module is imported by a
// CLIENT component, so it must stay free of node:fs — the disk read lives in
// ../keywords/loader.ts.
export interface CompetitorConfig {
  competitors: {
    domain: string;
    name: string;
    /** Keywords this rival overlaps with ours — used to fill the keyword
     *  sheet's "Competitors" column. Present in the committed config. */
    overlapKeywords?: string[];
    evidence?: string;
  }[];
  keywords: string[];
}

export type CompetitorTrend = 'up' | 'down' | 'flat' | 'new' | 'gone' | 'no-data';

export interface CompetitorRow {
  domain: string;
  name: string;
  query: string;
  latestRank: number | null;
  prevRank: number | null;
  delta: number | null;
  trend: CompetitorTrend;
  latestDate: string | null;
  prevDate: string | null;
  /** The competitor's landing URL in the latest snapshot — null when it was
   *  not in the Top-100 that day. Optional so hand-built rows in tests and
   *  older series files still type-check. */
  url?: string | null;
}

export interface CompetitorSeriesData {
  $schema: string;
  _readme: string[];
  generatedAt: string;
  d0: string;
  config: CompetitorConfig;
  snapshots: number;
  matrix: CompetitorRow[];
  totals: {
    snapshots: number;
    pairs: number;
    up: number;
    down: number;
    new: number;
    gone: number;
    noData: number;
  };
}

export const COMPETITOR_SERIES_PATH = 'data/competitor-series.json';

export const TREND_LABEL: Record<CompetitorTrend, string> = {
  up: '上升',
  down: '下降',
  flat: '持平',
  new: '新进Top100',
  gone: '掉出Top100',
  'no-data': '无数据',
};

export type CompSortKey = 'delta' | 'latestRank' | 'query' | 'name';
export type CompSortDir = 'asc' | 'desc';

export function sortCompetitorRows(
  rows: CompetitorRow[],
  key: CompSortKey,
  dir: CompSortDir,
): CompetitorRow[] {
  const mul = dir === 'asc' ? 1 : -1;
  const INF = Number.POSITIVE_INFINITY;
  const val = (r: CompetitorRow): number | string => {
    switch (key) {
      case 'delta':
        return r.delta ?? INF;
      case 'latestRank':
        return r.latestRank ?? INF;
      case 'query':
        return r.query;
      case 'name':
        return r.name;
    }
  };
  return rows.slice().sort((a, b) => {
    const va = val(a);
    const vb = val(b);
    if (va === INF || vb === INF) {
      if (va === INF && vb === INF) return 0;
      return va === INF ? 1 : -1;
    }
    if (typeof va === 'string' || typeof vb === 'string') {
      return String(va).localeCompare(String(vb)) * mul;
    }
    if (va === vb) return a.domain.localeCompare(b.domain);
    return (va - vb) * mul;
  });
}
