// src/lib/keywords/series.ts
// Types + pure helpers for data/keyword-series.json.
//
// That file is GENERATED by scripts/build-keyword-series.mjs, which stitches the
// raw snapshots in 数据分析/ into a comparable keyword × date series. It is not
// hand-edited — to change the numbers, re-run the fetch scripts and rebuild:
//
//   npm run fetch:bing && npm run fetch:gsc && npm run build:keywords
//
// The two sources are deliberately kept separate because they are NOT equally
// trustworthy: Bing gives a usable (if short) history, while the GSC exports
// were taken with inconsistent windows and cannot be compared across days.
//
// This module is imported by CLIENT components, so it must stay free of
// node:fs — the filesystem read lives in ./loader.ts.

export interface KeywordPoint {
  date: string;
  clicks: number;
  impressions: number;
  clickPosition: number | null;
  impressionPosition: number | null;
  fetchedAt: string;
}

export interface KeywordRow {
  query: string;
  points: KeywordPoint[];
  latest: KeywordPoint | null;
  previous: KeywordPoint | null;
  /** previous.position − latest.position. Positive = moved UP. */
  delta: number | null;
  /** Days between the two compared observations. */
  spanDays: number | null;
  observations: number;
}

/** Human-entered "why did this move" note. Stored in data/keyword-reasons.json,
 *  read separately from the generated series (the series has no reasons). */
export interface KeywordReason {
  query: string;
  date: string;
  reason: string;
}

/** query -> most recent reason (sorted by date desc, first wins). */
export function latestReasonByQuery(reasons: KeywordReason[]): Map<string, KeywordReason> {
  const m = new Map<string, KeywordReason>();
  const sorted = reasons
    .slice()
    .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
  for (const r of sorted) {
    if (!m.has(r.query)) m.set(r.query, r);
  }
  return m;
}

export interface BingSeries {
  label: string;
  snapshots: number;
  firstFetch: string;
  lastFetch: string;
  observations: number;
  droppedJunk: number;
  weeks: string[];
  keywords: KeywordRow[];
  totals: {
    keywords: number;
    comparable: number;
    up: number;
    down: number;
    flat: number;
    singlePoint: number;
    droppedJunk: number;
  };
  caveats: string[];
}

export interface GscWindow {
  fetchedAt: string;
  start: string | null;
  end: string | null;
  windowDays: number | null;
  rows: number;
}

export interface GscPoint {
  date: string;
  position: number | null;
  clicks: number;
  impressions: number;
  ctr: number | null;
  windowDays: number | null;
}

export interface GscRow {
  query: string;
  points: GscPoint[];
  latest: GscPoint | null;
  observations: number;
}

export interface GscSeries {
  label: string;
  snapshots: number;
  windows: GscWindow[];
  distinctWindowDays: number[];
  /** False when the exports used different window lengths — then cross-day
   *  comparison is meaningless and the UI must say so rather than average. */
  comparable: boolean;
  keywords: GscRow[];
  totals: { keywords: number; multiPoint: number };
  caveats: string[];
}

export interface KeywordSeriesData {
  $schema: string;
  _readme: string[];
  generatedAt: string;
  d0: string;
  bing: BingSeries | null;
  gsc: GscSeries | null;
}

const SERIES_PATH = 'data/keyword-series.json';

/** Where the generated series lives, relative to the repo root. */
export const KEYWORD_SERIES_PATH = SERIES_PATH;

/** A row is "moving" when we have two comparable observations that differ. */
export function isMoving(k: KeywordRow): boolean {
  return k.delta !== null && k.delta !== 0;
}

/** Sort keys offered by the table. Kept here so the UI and tests agree. */
export type SortKey = 'delta' | 'position' | 'impressions' | 'observations' | 'query';
export type SortDir = 'asc' | 'desc';

export function sortRows(rows: KeywordRow[], key: SortKey, dir: SortDir): KeywordRow[] {
  const mul = dir === 'asc' ? 1 : -1;
  const INF = Number.POSITIVE_INFINITY;
  const val = (k: KeywordRow): number | string => {
    switch (key) {
      case 'delta':
        // Nulls (no baseline) are flagged with INF below; the comparator makes
        // them sink regardless of direction.
        return k.delta === null ? INF : k.delta;
      case 'position':
        return k.latest?.impressionPosition ?? INF;
      case 'impressions':
        return -(k.latest?.impressions ?? 0);
      case 'observations':
        return -k.observations;
      case 'query':
        return k.query;
    }
  };
  return rows.slice().sort((a, b) => {
    const va = val(a);
    const vb = val(b);
    // Sentinel rows (no baseline / no rank) always sink to the bottom in BOTH
    // directions, so the table never buries real movers under blanks.
    if (va === INF || vb === INF) {
      if (va === INF && vb === INF) return 0;
      return va === INF ? 1 : -1;
    }
    if (typeof va === 'string' || typeof vb === 'string') {
      return String(va).localeCompare(String(vb)) * mul;
    }
    if (va === vb) return a.query.localeCompare(b.query);
    return (va - vb) * mul;
  });
}
