// src/app/[locale]/admin/keywords/page.tsx
// Keyword ranking panel — the actual data table the SEO/GEO board never showed.
//
// Thin shell: read data/keyword-series.json (generated by
// scripts/build-keyword-series.mjs) and hand it to the client table.
import { KeywordPanel } from '@/components/keywords/KeywordPanel';
import { loadKeywordSeries, loadKeywordReasons } from '@/lib/keywords/loader';

export const dynamic = 'force-dynamic';

export default async function KeywordsPage() {
  const data = loadKeywordSeries();
  const reasons = loadKeywordReasons();

  if (!data) {
    return (
      <div className="space-y-4">
        <h1 className="text-2xl font-semibold tracking-tight text-gray-900 dark:text-gray-100">关键词排名</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          尚未生成 <code className="rounded bg-gray-100 px-1 dark:bg-white/10">data/keyword-series.json</code>。
          先抓取原始数据，再合并成序列：
        </p>
        <pre className="rounded-xl border border-gray-200 bg-gray-50 p-4 text-xs leading-relaxed text-gray-700 dark:border-white/10 dark:bg-white/[0.04] dark:text-gray-200">
{`npm run fetch:bing      # 抓 Bing Webmaster（需 BING_WEBMASTER_API_KEY）
npm run fetch:gsc       # 抓 Google Search Console
npm run build:keywords  # 合并成可比序列`}
        </pre>
      </div>
    );
  }

  return <KeywordPanel data={data} reasons={reasons} />;
}
