export const slug = 'epub-to-pdf';
export const title = 'Free EPUB to PDF Converter — No Sign-up';
export const level = 'A' as const;
export const wordCount = 2000;

export const content = {
  hero: {
    title: 'EPUB to PDF - From Fluid Reading to Fixed Layout',
    subtitle: 'Free EPUB to PDF converter. No sign-up — turn reflowable ebooks into print-ready PDFs for sharing and citation.'
  },

  sections: [
    {
      heading: 'When Do You Need to Convert EPUB to PDF?',
      body: 'EPUB is known for its reflowable layout — perfect for screen reading. But some scenarios require fixed-layout PDF: Print Output — PDF ensures print results match screen display without layout chaos. Academic Citation — Academic papers and book excerpts need precise page numbers; PDF fixed layout naturally supports this. Formal Document Sharing — Contracts, reports, presentation materials in formal scenarios; PDF is the safest sharing format. Archive Preservation — PDF/A is an international standard for long-term archival, more suitable for permanent storage than EPUB.'
    },
    {
      heading: 'Technical Challenges in EPUB to PDF Conversion',
      body: 'EPUB uses reflowable layout while PDF uses fixed layout — their design philosophies are completely different. Conversion requires: Smart Page Breaking — Avoid paragraph truncation at page boundaries. Font Embedding — Ensure consistent display across different devices. Image Resolution Adjustment — PDF typically needs higher DPI. Header/Footer Addition — Page numbers, book titles. Our converter automatically handles these issues, generating professional PDF output.'
    },
    {
      heading: 'PDF vs EPUB Use Case Comparison',
      body: `| Use Case | Recommended Format | Reason |
|----------|-------------------|--------|
| Daily Reading | EPUB | Reflowable, night mode, adjustable font |
| Printing | PDF | Fixed layout, exact pagination |
| Academic Citation | PDF | Precise page numbers |
| Cross-Device Sync | EPUB | Native support |
| Long-term Archive | PDF/A | International standard |
| Mobile Reading | EPUB | Adapts to screen size |
| Formal Submission | PDF | Universal compatibility |

If unsure, download both formats — we provide simultaneous download option.`
    },
    {
      heading: 'Conversion Quality Guarantee',
      body: 'Our converter performs intelligent processing: Automatic Pagination — Smart break points avoid cutting paragraphs or images. Font Embedding — All fonts embedded in PDF for consistent rendering. Image Optimization — Maintain original quality while optimizing for print. Navigation Generation — Create clickable bookmarks from EPUB table of contents. Metadata Preservation — Title, author, ISBN written to PDF metadata. Calibre engine has been validated through thousands of successful conversions.'
    },
    {
      heading: 'Common Scenarios',
      body: `Convert EPUB to PDF when you need to: Print a book chapter for offline reading. Submit documents to academic journals or publishers. Share formatted content with colleagues who prefer PDF. Create presentation slides from book excerpts. Archive important books in PDF/A format for long-term preservation.

Keep EPUB for daily reading on phones, tablets, and e-readers.`
    },
    {
      heading: 'Why Does Converting EPUB to PDF Shrink the Viewing Area?',
      body: `EPUB reflows to fill any screen, but PDF locks content onto fixed pages, usually A4 or Letter. When the converter maps your fluid text onto that fixed page, it applies default margins and a fixed page width, so the readable area can look smaller than what you saw while reading the EPUB. The text is not cropped or lost — it simply sits inside a print-page frame.

To keep the viewing area closer to your original, set a smaller margin and a larger page size before converting, or use a converter that exposes those options. BookConv preserves your images and layout and applies sensible default margins, so most books land within a normal print frame.`
    },
    {
      heading: 'Convert EPUB to PDF on Linux (Command Line)',
      body: `On Linux you can convert without a desktop GUI using Calibre's command-line tool. The command ebook-convert input.epub output.pdf turns an EPUB into a PDF directly, and you can add flags to control margins and page size.

If you prefer not to install desktop software, BookConv runs the same Calibre engine in the browser — open the EPUB to PDF converter on any Linux machine and convert online with no install.`
    }
  ],

  faq: [
    { q: 'Are page numbers in converted PDF accurate?', a: 'Yes. Our converter adds correct page numbers to each PDF page maintaining correspondence with original content. This is crucial for academic citation.' },
    { q: 'Can image-type PDF be converted back to EPUB?', a: 'Yes but quality depends on image clarity. If PDF was generated by scanning (image-type) OCR recognition is needed first before text extraction and EPUB conversion.' },
    { q: 'Will PDF file be very large?', a: 'File size depends on content. Plain text EPUB to PDF usually increases only 20-30% in size. If original book contains numerous high-resolution images PDF will be 2-5x larger than EPUB.' },
    { q: 'How long does EPUB to PDF conversion take?', a: 'For most EPUB files under 100 pages conversion takes 15-45 seconds. Complex files with numerous images may take 1-3 minutes.' },
    { q: 'Does conversion preserve images?', a: 'Yes. All embedded images are correctly extracted and packaged into PDF with original resolution and positioning.' },
    { q: 'Why does converting EPUB to PDF result in smaller viewing area?', a: 'PDF fixes content onto a print page with default margins, so the readable area looks smaller than a fluid EPUB screen. The text is not lost — adjust page size or margins, or use a converter that exposes those settings.' },
    { q: 'How do I convert EPUB to PDF on Linux?', a: 'Use Calibre command line: ebook-convert input.epub output.pdf. For a no-install option, BookConv runs the same engine in the browser — open the EPUB to PDF converter on any Linux machine.' }
  ]
};
