export const slug = "ai-feeding-notebooklm-chatgpt";
export const title = "AI Feeding: Import NotebookLM and ChatGPT Content to Ebook";
export const date = "2026-08-26";
export const author = "BookConv Team";
export const tags = ["NOTEBOOKLM", "CHATGPT", "EPUB", "PDF", "EBOOK", "AI", "IMPORT"];

export const content = {
  intro: `Artificial intelligence has revolutionized how we generate, consume, and share information. If you have been using tools like Google's NotebookLM or OpenAI's ChatGPT to create content, you likely want to share that valuable knowledge in a portable format. AI feeding, or the process of importing AI-generated content into ebook converters, allows you to transform raw text from these platforms into professional eBooks ready for Kindle, iPad, or any other device.`,
  sections: [
    { heading: "Understanding AI Feeding in Ebook Conversion", body: `AI feeding refers to the workflow of taking structured or unstructured content generated by large language models and preparing it for ebook distribution. Unlike traditional writing, AI-generated text often comes with markdown formatting, conversational structures, or metadata that needs cleanup before conversion. For a quality checklist to verify your converted AI content, see our [check converted file quality guide](/blog/check-converted-file-quality). If you need to convert PDFs with OCR for AI-fed content, try our [scanned PDF to EPUB with OCR guide](/blog/scanned-pdf-to-epub-ocr).` },
    {
      heading: `Key Takeaways`,
      body: `- **AI 内容需要清理后再转换。** 大模型生成的文本常带 markdown 标记、对话式结构或冗余元数据，直接转换会把这些杂质一起带进电子书。
- **格式检查有独立清单。** 转换后按 [check converted file quality](/blog/check-converted-file-quality) 逐项验证，比反复重转高效。
- **扫描件走 OCR 路线。** AI 喂养的内容若来自 PDF 扫描件，先看 [scanned PDF to EPUB with OCR](/blog/scanned-pdf-to-epub-ocr)，OCR 质量决定了后续所有环节。
- **先清理结构，再谈格式。** 章节标记和标题层级没理清之前，任何转换器都只能把混乱原样搬运。`
    }
  ]
};

export const faqs = [
  { question: "Can I convert ChatGPT output directly to EPUB?", answer: "Yes, but you should first clean the markdown formatting and remove conversational filler phrases." },
];