export const slug = "ai-feeding-notebooklm-chatgpt";
export const title = "AI Feeding: Import NotebookLM and ChatGPT Content to Ebook";
export const date = "2026-08-26";
export const author = "BookConv Team";
export const tags = ["NOTEBOOKLM", "CHATGPT", "EPUB", "PDF", "EBOOK", "AI", "IMPORT"];

export const content = {
  intro: `Artificial intelligence has revolutionized how we generate, consume, and share information. If you have been using tools like Google's NotebookLM or OpenAI's ChatGPT to create content, you likely want to share that valuable knowledge in a portable format. AI feeding, or the process of importing AI-generated content into ebook converters, allows you to transform raw text from these platforms into professional eBooks ready for Kindle, iPad, or any other device.`,
  sections: [
    { heading: "Understanding AI Feeding in Ebook Conversion", body: `AI feeding refers to the workflow of taking structured or unstructured content generated by large language models and preparing it for ebook distribution. Unlike traditional writing, AI-generated text often comes with markdown formatting, conversational structures, or metadata that needs cleanup before conversion.` }
  ]
};

export const faqs = [
  { question: "Can I convert ChatGPT output directly to EPUB?", answer: "Yes, but you should first clean the markdown formatting and remove conversational filler phrases." },
];