export const slug = `sitemap-seo-guide`;
export const title = `Sitemaps and SEO: How Search Engines Find Every BookConv Page`;
export const date = `2026-07-30`;
export const author = "BookConv Team";
export const tags = ["SEO", "sitemap", "search-console", "technical"];

export const content = {
  intro: `A sitemap is the shortest route between a page you published and a search engine that hasn't noticed it yet. Here's what BookConv's sitemap contains, how to submit one to Google Search Console, and the mistakes that quietly keep pages out of the index.`,
  sections: [
    {
      heading: `What a Sitemap Does, and What It Doesn't`,
      body: `A sitemap is an XML file listing the URLs on your site that you want search engines to know about. Each entry carries the address plus a few optional hints: when the page last changed, how often it tends to change, and how important it is relative to your other pages.

Crawlers find pages mainly by following links. That works well for anything linked from your homepage, and badly for pages buried three clicks deep. A sitemap short-circuits discovery — it hands over the full list instead of hoping a crawler stumbles across everything.

Now the honest part. A sitemap doesn't make Google index a page, and it doesn't improve rankings. Google is explicit about this in its [guide to building and submitting a sitemap](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap): being listed makes a URL known, not necessarily worth indexing.

That's still valuable. A page that's never crawled can't rank at all. Everything after that — useful content, sensible titles, internal links — decides whether it earns a position.

For a converter site the payoff sits in the tool pages. Each format pair is a distinct thing people search for, and someone looking to [turn a PDF into an EPUB](/convert/pdf-to-epub) will never see that page if it was never crawled.`
    },
    {
      heading: `What's Inside the BookConv Sitemap`,
      body: `Our sitemap isn't a static file someone remembers to update. It's generated by code at build time, using the same data the site itself renders from. Next.js supports this through a sitemap file in the app directory that returns a list of URL entries, documented in the [Next.js sitemap reference](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap).

Because it reads from live data, adding a conversion pair or publishing a post puts the URL in the sitemap on the next deploy. There's no separate step to forget.

### What gets listed

The generator walks both locales we ship — English at the site root and Spanish under an /es prefix — and emits every public URL for each:

- **The homepage**, marked as weekly and given top priority since it's the main entry point
- **Pricing**, updated monthly, and the **blog index**, updated weekly
- **Privacy and terms** pages, marked yearly with low priority — needed, but not what anyone searches for
- **Every conversion tool page** under /convert/, refreshed monthly, with the main format pairs weighted slightly above the long-tail ones
- **Every blog post**, using the post's own publication date as its last-modified value

Priority values are relative signals within your own site, not a score anyone else sees. They express which pages you consider central. We put the homepage and the heavily used pairs like [EPUB to MOBI](/convert/epub-to-mobi) above legal pages, which is roughly how visitors treat them too.

The whole file is served at /sitemap.xml. If you want the formal definition of the format — allowed tags, size limits, encoding rules — [sitemaps.org](https://www.sitemaps.org/protocol.html) is the source everyone implements against.`
    },
    {
      heading: `Submitting Your Sitemap to Google Search Console`,
      body: `Publishing the file is step one. Telling Google about it is step two, and it takes about a minute.

1. **Verify ownership** of the property in Google Search Console. Domain-level verification through a DNS record covers every subdomain and both http and https, so it's usually the least painful option.
2. **Open the Sitemaps report** in the left-hand navigation of your property.
3. **Enter the path**, typically just sitemap.xml — the field is already scoped to your verified domain.
4. **Submit**, then leave it alone. Status moves to Success once the file has been fetched and parsed. Fetching is quick; indexing the URLs inside is not.
5. **Check back in a week or two** and compare discovered URLs against what you expected to see.

You only submit once. Google re-fetches the file periodically on its own, so a rebuilt sitemap doesn't need resubmitting after every deploy.

### Reading the results without panicking

The Pages report will always show some URLs as discovered but not indexed. That's normal — it means Google knows about the page and hasn't decided it's worth storing yet. Thin pages, near-duplicates, and brand-new URLs sit in that bucket routinely.

What deserves attention is a sudden change: previously indexed pages dropping out, or a spike in fetch errors. Steady-state noise isn't worth chasing. Trend breaks are. And timelines vary — a new site can wait weeks for meaningful coverage. Submitting again won't speed it up.`
    },
    {
      heading: `robots.txt: The Other Half of the Job`,
      body: `A sitemap says which pages you want found. robots.txt says which paths crawlers should stay out of. They work as a pair, and a conflict between them wastes crawl budget or hides content.

Ours does three things. It allows crawling of the content areas — the conversion tools, the blog, pricing. It blocks paths that have no business in search results: the API routes, the auth flow, and the framework's internal build assets. And it names the sitemap location outright, so any crawler that reads the file learns where the URL list lives without being told separately.

That last line matters more than it looks. Search Console submission covers Google; the robots.txt reference covers every other compliant crawler. Google's [robots.txt documentation](https://developers.google.com/search/docs/crawling-indexing/robots/intro) explains how the directives are interpreted.

One rule catches people out constantly: **never list a URL in your sitemap that robots.txt blocks.** You're simultaneously asking a crawler to look at a page and forbidding it from doing so. Search Console flags the contradiction, and the page ends up in limbo. Pick one — either it's public and in the sitemap, or it's blocked and out of it.

The same logic applies to canonical URLs. Every sitemap entry should be the canonical version of that page: same protocol, same subdomain, same trailing-slash convention. Listing a URL that redirects or canonicalises elsewhere sends a mixed signal about which address is real.`
    },
    {
      heading: `Sitemap Mistakes That Quietly Cost You Traffic`,
      body: `Most sitemap problems don't announce themselves. The file validates, Search Console says Success, and pages still don't show up. These are the usual reasons:

1. **Stale entries.** URLs for pages you deleted turn into soft 404s. If your sitemap is generated from live data this fixes itself; hand-maintained lists rot within months.
2. **Relative paths.** Every entry needs the full absolute URL including the protocol. Relative paths are invalid in the sitemap format.
3. **Non-canonical duplicates.** Listing both the www and non-www version, or both trailing-slash variants, splits signals between addresses that should be one page.
4. **Blocked URLs included anyway.** The robots.txt contradiction described above, which is common enough to be worth checking twice.
5. **Private pages exposed.** Anything behind a login returns an error to a crawler and burns fetches for nothing. Keep authenticated routes out.
6. **Uniform priority.** Setting everything to 1.0 conveys exactly as much information as setting everything to 0.5 — which is none.
7. **Missing translated versions.** If you ship multiple locales, each one needs its own entries. A sitemap covering only English leaves the rest of the site undiscovered.
8. **Fake last-modified dates.** Stamping every URL with today's date on every build teaches crawlers to ignore the field. Use the date the content actually changed, which is why our blog entries carry the post's own date.

Two of these are worth automating rather than remembering: generate from live data, and use one canonical URL builder everywhere. That kills stale entries and duplicate variants in one move — the same argument we make about conversion pipelines in [our guide to webhook-driven automation](/blog/webhook-integration).`
    },
    {
      heading: `Key Takeaways`,
      body: `- **A sitemap aids discovery, not ranking.** It gets pages crawled; content and links decide whether they place.
- **Generate it from live data** so new tool pages and posts appear automatically instead of depending on someone updating a list.
- **Submit once in Search Console** and let Google re-fetch on its own — resubmitting after every deploy accomplishes nothing.
- **Keep robots.txt consistent** with the sitemap, and reference the sitemap location inside robots.txt for crawlers beyond Google.
- **Use honest metadata.** Real last-modified dates and differentiated priorities carry signal; uniform values carry none.`
    },
    {
      heading: `Frequently Asked Questions`,
      body: `Q: Do I need a sitemap if my site is small?
A: A well-linked site under a hundred pages will usually get crawled fine without one. It still costs nothing to add, and it helps the moment you publish something that isn't linked from the main navigation.

Q: How often should the sitemap be regenerated?
A: Every build, if it's generated from code. Ours rebuilds with the site, so the deploy that ships a new page also ships the sitemap entry for it.

Q: Does a higher priority value make a page rank better?
A: No. Priority is a relative hint about which of your pages matter most to you, used at most as a crawl-ordering signal. It has no effect on ranking, and search engines are free to ignore it.

Q: What if Search Console says pages are discovered but not indexed?
A: That's a normal state, not a failure. It means the URL is known and hasn't been selected for the index. Usually the fix is making the page more distinct and useful, or linking to it better from pages that already perform well.

Q: Should each language have its own sitemap?
A: Not necessarily. A single sitemap can hold every locale, which is how ours works — both language variants are listed in the same file. Splitting by locale only helps once the file gets large enough to be awkward.

Q: Can I include pages that are blocked in robots.txt?
A: You can, but you shouldn't. The two instructions contradict each other and Search Console will report the conflict. Decide whether the page is public, then make both files agree.

Q: What about Bing and other search engines?
A: Bing has its own webmaster tools with an equivalent submission flow, and most crawlers find the sitemap through the robots.txt reference anyway. The file itself needs no changes.`
    }
  ]
};
